### ISSUE TITLE
Variable $fz-base have been overwritted by settings-compat-v7

### ISSUE THREAD

**Issue by carlesnunez** [SUI-Components/sui-theme#137]
**What is the issue?**
The issue is that when we are not re-setting the $fz-base variable on our portal themes the value of that variable is 14.

**What should be the expected behavior?**
The expected content for the variable $fz-base should be 16px.

**Why is this happening?**
If we check the index.scss file we found the follow:

<img width="271" alt="screen shot 2017-12-04 at 18 02 28" src="https://user-images.githubusercontent.com/5639972/33565556-b58b2d0c-d91d-11e7-9edd-8e33c1aa1af2.png">

As we are setting our variable as default on settings-compat-v7:
<img width="179" alt="screen shot 2017-12-04 at 18 02 12" src="https://user-images.githubusercontent.com/5639972/33565585-cdcb865a-d91d-11e7-9f82-88f5f85395aa.png">

And in _settings.scss:
<img width="325" alt="screen shot 2017-12-04 at 18 02 02" src="https://user-images.githubusercontent.com/5639972/33565611-e4b7e73c-d91d-11e7-8cbd-76a04bbed662.png">

The behavior of scss sets that if two variables are defined with the same name and as default the first declared is the one that wins:
[Click here for a live demo](https://www.sassmeister.com/gist/de9f763fbd947e75f4ba9099a53f54f3)

**Comment by JoanClaret** [comment]
Since we are overwritting this value in each vertical, i would suggest to set the same value in both cases (`settings`, and `settings-compat`).

Anyways, the best option may be refactor all components using font-size compat declarations and get rid of this compat fonts.
