### ISSUE TITLE
The variable step is ambiguous or could lead us to false errors.

### ISSUE THREAD

**Issue by carlesnunez** [SUI-Components/sui-theme#154]
### Whats the 'issue'?
 Given the next scenario - I have a marketplace theme with the next color.js code:

```scss
$c-primary: #30923E;
````

If I use `$c-primary-dark` it will show the dark color of the sui-theme $c-primary, no the marketplace theme $c-primary.

### Why does it happen?

As SASS is not dynamic and we are using a color-variation function. Each change in any variable implicated on a function call (in this case color-variation) must be followed by a re-definiton of all the variables that implement it.(in this case $c-primary-dark).

So... assuming this behavior.... whats the point of have a composed variable as $c-primary-dark is if we will NEVER should use it in its default color form if we do not make an import of the marketplace-specific theme BEFORE the sui-theme?

Don't know if I've done a well explanation so if you want to see a live example you can ask me for it.

**Comment by jcger** [comment]
Yes, please add a live example

**Comment by davidbarna** [comment]
It may come from the way you handle inheritance from sui-theme.
sui-theme's variables should be loaded AFTER your project's variables. The only right way to handle inheritance in sass is this one:

```sass
// sui-theme sass
$c-primary: blue !default;
$c-primary-dark: darken($c-primary, 20) !default;
```

```sass
// Your sass
$c-primary: red;

@import 'sui-theme'
```

If you see different implementations, they're mistaken.

**Comment by carlesnunez** [comment]
I understood your explanation @davidbarna in any case there are some concerns about how we 'override' that I'd like to talk with you. 

In any case I'll re-open the issue if our conversation decide it.
