### ISSUE TITLE
Gradients generator Mixin

### ISSUE THREAD

**Issue by davecarter** [SUI-Components/sui-theme#53]
Given a color we need to be able to generate a set of lighter or darker color variations using a mixin.
This mixin should maintain color hue and saturation and generate this variation modifying lightness value only.

Lets say UX provide a $primary color and a set of lighter and darker values as shown in the caption below. This mixin will must provide the automated variations so we'll be able to map them later in a list of Sass vars:

```
$c-primary-l1: color-variation($c-primary, step-l1)
$c-accent-l2: color-variation($c-accent, step-l2)
```

![lightnessgradients](https://cloud.githubusercontent.com/assets/10925540/25427356/9cb31218-2a72-11e7-8f10-af7a1842bece.png)

**Comment by naxhh** [comment]
I know nothing about this. but isn't hsla a good thing for this?

**Comment by davecarter** [comment]
Indeed, the reason why we need this mixin is because all color values that we have are stored in #HEX format as you can see [here](https://github.com/SUI-Components/theme-basic/blob/master/src/_settings.scss#L30).

**Comment by julian-gernun** [comment]
@davecarter can this be closed?

**Comment by davecarter** [comment]
yes!
actually this feature was developed and merged [here](https://github.com/SUI-Components/sui-theme/pull/58) a while ago
